# Generated by Django 5.0.6 on 2024-06-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.IntegerField(max_length=200)),
                ('Campaña', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encargado', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicio', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Estado', models.CharField(max_length=200)),
                ('Causa_negacion', models.CharField(max_length=200)),
                ('Cobro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.cobro')),
                ('Nota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.notas')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Nuevo', models.CharField(max_length=200)),
                ('Sector', models.CharField(max_length=200)),
                ('Canal', models.CharField(max_length=200)),
                ('Contacto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.contacto')),
                ('Licitacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.licitacion')),
            ],
        ),
    ]
