# Generated by Django 5.0.6 on 2024-06-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobro',
            name='Monto',
        ),
    ]
