# Generated by Django 5.0.6 on 2024-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0002_remove_cobro_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes', models.CharField(max_length=200)),
                ('Cliente', models.CharField(max_length=200)),
                ('Nuevo', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Estado', models.CharField(max_length=200)),
                ('Pago_mensual', models.CharField(max_length=200)),
                ('Sector', models.CharField(max_length=200)),
                ('Causal_negacion', models.CharField(max_length=200)),
                ('Observaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='licitacion',
            name='Cobro_id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='Contacto_id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='Licitacion_id',
        ),
        migrations.RemoveField(
            model_name='licitacion',
            name='Nota_id',
        ),
        migrations.DeleteModel(
            name='Cobro',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Licitacion',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
