# Generated by Django 5.0.6 on 2024-07-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0003_informe_remove_licitacion_cobro_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='Por_campaña',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
