# Generated by Django 5.0.6 on 2024-07-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0007_remove_informe_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='Observaciones',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
