# Generated by Django 5.0.6 on 2024-07-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0010_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telefono', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Email',
            new_name='Nuevo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='Telefono',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='informe',
            name='Id_empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Id_contacto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.contacto'),
        ),
    ]
