# Generated by Django 5.0.6 on 2024-07-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0011_contacto_rename_email_empresa_nuevo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='Id_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.contacto'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='Id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.empresa'),
        ),
    ]
