# Generated by Django 5.0.6 on 2024-07-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0014_alter_informe_id_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='Encargado',
        ),
        migrations.AddField(
            model_name='contacto',
            name='Encargado',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
