# Generated by Django 5.0.6 on 2024-07-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0015_remove_empresa_encargado_contacto_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='Id_empresa',
        ),
    ]
