# Generated by Django 5.0.6 on 2024-07-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0019_alter_empresa_id_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='Id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.empresa'),
        ),
    ]
