# Generated by Django 5.0.6 on 2024-07-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0022_remove_contacto_id_empresa_empresa_id_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informe',
            new_name='Ofertas',
        ),
    ]
