# Generated by Django 5.0.6 on 2024-07-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0023_rename_informe_ofertas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='Id_contacto',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='Nuevo',
        ),
        migrations.RemoveField(
            model_name='ofertas',
            name='Id_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='Email',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Encargado',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Telefono',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='Cliente',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
