# Generated by Django 5.0.6 on 2024-07-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0024_remove_empresa_id_contacto_remove_empresa_nuevo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='Contacto',
        ),
    ]
