# Generated by Django 5.0.6 on 2024-08-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0026_notas_ofertas_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='Observaciones',
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='notas',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.notas'),
        ),
    ]
