# Generated by Django 5.0.6 on 2024-08-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0028_alter_ofertas_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='notas',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
