# Generated by Django 5.0.6 on 2024-08-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0030_notas_ofertas_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='Cliente',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.empresa'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Por_campaña',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
