# Generated by Django 5.0.6 on 2024-08-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0031_alter_ofertas_cliente_alter_ofertas_por_campaña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='notas',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
