# Generated by Django 5.0.6 on 2024-08-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0032_alter_notas_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='Nuevo',
        ),
        migrations.AddField(
            model_name='empresa',
            name='Nuevo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Canal_medio',
            field=models.CharField(default='l', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Causal_negacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Estado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Mes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Pago_mensual',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='Sector',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
