# Generated by Django 5.0.6 on 2024-08-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0033_remove_ofertas_nuevo_empresa_nuevo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='notas',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='notas',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
