# Generated by Django 5.0.6 on 2024-08-14 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0034_rename_notas_notas_descripcion_notas_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertas',
            name='notas',
        ),
        migrations.AddField(
            model_name='empresa',
            name='notas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.notas'),
        ),
    ]
