# Generated by Django 5.0.6 on 2024-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0035_remove_ofertas_notas_empresa_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='Anio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
