# Generated by Django 5.0.6 on 2024-08-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0036_ofertas_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='notas',
        ),
        migrations.AddField(
            model_name='notas',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.empresa'),
        ),
    ]
