# Generated by Django 5.0.6 on 2024-08-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0037_remove_empresa_notas_notas_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='empresa',
        ),
    ]
