# Generated by Django 5.0.6 on 2024-08-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0038_remove_notas_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='notas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.notas'),
        ),
    ]
