# Generated by Django 5.0.6 on 2024-08-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0041_alter_empresa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='Estado',
        ),
    ]
