# Generated by Django 5.0.6 on 2024-08-16 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0044_remove_ofertas_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='ofertas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Area_comercial.ofertas'),
        ),
    ]
