# Generated by Django 5.0.6 on 2024-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_comercial', '0045_notas_ofertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
